#!/bin/bash
#PBS -N vB_T_0p02__Didx_1_1__typ
#PBS -l nodes=1:ppn=4
#PBS -l walltime=08:00:00
#PBS -l mem=8gb
#PBS -o /home/2/kj405942/Byczuk_Freericks/filling_variantB_freericks/pbs_variantB_T002_typ_21x21_mu20/chunks/T_0p02__Didx_1_1__typ/job.out
#PBS -e /home/2/kj405942/Byczuk_Freericks/filling_variantB_freericks/pbs_variantB_T002_typ_21x21_mu20/chunks/T_0p02__Didx_1_1__typ/job.err
cd '/home/2/kj405942/Byczuk_Freericks/filling_variantB_freericks'
python3 solve_variantB_dmft.py --T-list '0.02' --w1-list '0.5,0.45,0.4' --U-min 0.0 --U-max 5.0 --n-U 21 --Delta-list '0.2975' --kind 'typ' --omega0 8 --n-omega 301 --n-eps 31 --eta 1e-3 --max-iter 850 --tol 2e-3 --mix 0.15 --mu-min -8 --mu-max 8 --ne-tol 5e-3 --max-mu-iter 70 --mu-accept-diff 2e-3 --workers 4 --out '/home/2/kj405942/Byczuk_Freericks/filling_variantB_freericks/pbs_variantB_T002_typ_21x21_mu20/chunks/T_0p02__Didx_1_1__typ' --resume
